version: '3'
services:
  backend:
    build:
      context: ./melingo_backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:123456@postgres:5432/melingo-db

  frontend:
    build:
      context: ./melingo_frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: melingo-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

networks:
  mynetwork:
    driver: bridge